config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :answers do
    post 'click_count'
  end
  resources :presentations
  get 'qty/:id' => 'presentations#qty'

   root 'presentations#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :presentation
end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  has_many :answers , dependent: :destroy
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:update, :destroy]
  # GET /presentations/new
  def new
    @answer = Answer.new
    @presentations = Presentation.all
  end

  def create
    @answer = Answer.new(answer_params)
    @answer.click = 0
    respond_to do |format|
      if @answer.save
        format.html { redirect_to root_path, notice: 'Presentation was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presentations/1
  # PATCH/PUT /presentations/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to root_path, notice: 'Presentation was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1
  # DELETE /presentations/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Presentation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def click_count
    if params[:answer_id].present?
      @answer = Answer.find(params[:answer_id])
      count = 1
      @answer.click = count + @answer.click
      @answer.save
      redirect_to root_path, notice: "Gracias por tu Respuesta"
    else
      redirect_to root_path, notice: "Error, intentalo nuevamente"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:presentation_id, :question, :click)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :set_presentation, only: [:show, :edit, :update, :destroy, :qty]
  #before_action :authenticate_admin!

  # GET /presentations
  # GET /presentations.json
  def index
    @presentations = Presentation.all
  end

  # GET /presentations/1
  # GET /presentations/1.json
  def show
    @answers = @presentation.answers
  end

  # GET /presentations/new
  def new
    @presentation = Presentation.new
  end

  # GET /presentations/1/edit
  def edit
  end

  # POST /presentations
  # POST /presentations.json
  def create
    @presentation = Presentation.new(presentation_params)

    respond_to do |format|
      if @presentation.save
        format.html { redirect_to @presentation, notice: 'Presentation was successfully created.' }
        format.json { render :show, status: :created, location: @presentation }
      else
        format.html { render :new }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presentations/1
  # PATCH/PUT /presentations/1.json
  def update
    respond_to do |format|
      if @presentation.update(presentation_params)
        format.html { redirect_to @presentation, notice: 'Presentation was successfully updated.' }
        format.json { render :show, status: :ok, location: @presentation }
      else
        format.html { render :edit }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1
  # DELETE /presentations/1.json
  def destroy
    @presentation.destroy
    respond_to do |format|
      format.html { redirect_to presentations_url, notice: 'Presentation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def qty

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presentation_params
      params.require(:presentation).permit(:title, :description)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/answers/new.html.erb
<h1>Nueva Respuesta</h1>
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Respuesta' %><br>
    <%= f.text_field :question %>
  </div>
  <% if params[:presentation_id].present? %>
    <%= f.hidden_field :presentation_id, value: params[:presentation_id] %>
  <% else %>
    <div class="field">
      <%= f.label :presentation_id, "Alternativas" %><br>
      <%= f.collection_select :presentation_id, @presentations, :id, :title %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Volver', presentations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alterna</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/navbar' %>


<%= yield %>

</body>
</html>

app/views/presentations/_form.html.erb
<%= form_for(@presentation) do |f| %>
  <% if @presentation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@presentation.errors.count, "error") %> prohibited this presentation from being saved:</h2>

      <ul>
      <% @presentation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/presentations/edit.html.erb
<h1>Editing Presentation</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @presentation %> |
<%= link_to 'Volver', presentations_path %>

app/views/presentations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Preguntas</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <!-- <th>Description</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @presentations.each do |presentation| %>
      <tr>
        <td><%= link_to presentation.title, presentation %></td>
        <td><%= presentation.description %></td>
        <!-- <td></%=  'Show',  %></td> -->
        <%- if admin_signed_in? %>
          <td><%= link_to 'Editar', edit_presentation_path(presentation) %></td>
        <% end %>
        <%- if admin_signed_in? %>
          <td><%= link_to 'Eliminar', presentation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%#= link_to 'Respuestas', qty_path %>
<%- if admin_signed_in? %>
<%= link_to 'Nueva Pregunta', new_presentation_path %>
<% end %>

app/views/presentations/new.html.erb
<h1>New Presentation</h1>

<%= render 'form' %>

<%= link_to 'Volver', presentations_path %>

app/views/presentations/qty.html.erb
<h3>Resultados</h3>

  <h4><%= @presentation.title %></h4>
  <ul>
    <% @presentation.answers.each do |answer| %>
      <li> <%= answer.question%> | <%= answer.click %> Voto(s)</li>
    <% end %>
  </ul>


<%= link_to 'Volver', presentations_path %>

app/views/presentations/show.html.erb
<h2>Respuestas</h2>
<p id="notice"><%= notice %></p>

<% @answers.each do |answer| %>
  <%= button_to "#{answer.question}", answer_click_count_path(answer), method: :post%>
<% end %>
<br>
<%- if admin_signed_in? %>
	<%= link_to 'Nuevas Respuestas', new_answer_path(presentation_id: @presentation.id) %> |

<% end %>
</%= link_to 'Editar', edit_presentation_path(@presentation) %>
<%= link_to 'Volver', presentations_path %>

app/views/shared/_navbar.html.erb
<p>
	<% unless admin_signed_in? %>
		<%= link_to 'Ingresar', new_admin_session_path %>
		<%= link_to 'Registrar', new_admin_registration_path %>
	<% else %>
		<%= link_to current_admin.email, edit_admin_registration_path %>
		<%= link_to 'Salir', destroy_admin_session_path, method: :delete  %>
	<% end %>

</p>